package reversi;

import java.awt.Component;

/**
 *
 * @author Rimantas Silka (100094676)
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View(){
        initComponents();

        setSize(600, 527);
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    /**
     * Method to initialise board
     * @param board from model
     */
    public void initBoard(Model.Board board){
        this.add(board);
    }

    /**
     * Method to add a component to the board
     * @param component
     */
    public void addSomething(Component component){
        this.add(component);
        component.setVisible(true);
        pack();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
